version = 0.1

[default.deploy.parameters]
stack_name = "scrabble-puzzles"
resolve_s3 = true
s3_prefix = "scrabble-puzzles"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AllowedOrigin=\"https://master.ddfup0xv0rhdf.amplifyapp.com\""
image_repositories = []

[default.global.parameters]
region = "eu-west-2"
